#!/bin/bash

if [ -f $1 ]; then
    for((e=0; e <= 2; e++)); do
        for((b=0; b <= 1; b++)); do
            bin/bn-to-cnf $1 $e $b $vars
        done
    done

    for((vars=10; vars <= 13; vars++)); do
        for((b=0; b <= 1; b++)); do
            bin/bn-to-cnf $1 3 $b $vars
        done
    done

fi
